# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
